import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TabsNav from "@/components/ui/tabs-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="fixed inset-x-0 top-0 z-30">
          <div className="backdrop-blur-sm bg-black/30">
            <div className="container mx-auto px-6 py-3 flex items-center justify-between">
              <div className="text-lg font-semibold text-white">Cloudora <span className="text-slate-300">Tech</span></div>
              <nav>
                <TabsNav />
              </nav>
            </div>
          </div>
        </header>

        <div className="pt-20">{children}</div>
      </body>
    </html>
  );
}
